Repository olibos/HomeAssistant-RecycleApp, pull requests merged in 2024-01, with the labels that each got.

#40 Add samples templates
  README.md
  docs/images/entity-filter.png
  docs/images/templates.png
  docs/images/tomorrow.png
Labels: documentation

#42 Cleaning (Ruff & Co)
  custom_components/recycle_app/__init__.py
  custom_components/recycle_app/api.py
  custom_components/recycle_app/config_flow.py
  custom_components/recycle_app/const.py
  custom_components/recycle_app/sensor.py
Labels: enhancement

#43 Create sk.json
  custom_components/recycle_app/translations/sk.json
Labels: chore

#44 Collect calendar
  custom_components/recycle_app/__init__.py
  custom_components/recycle_app/api.py
  custom_components/recycle_app/calendar.py
  custom_components/recycle_app/config_flow.py
  custom_components/recycle_app/info.py
  custom_components/recycle_app/sensor.py
Labels: new-feature

#49 [v2.3.0-b2] - Recycling Park Calendar does not update correctly
  custom_components/recycle_app/recycling_park_calendar.py
Labels: bug [beta]

#50 [v2.3.0-b2] - Missing Collect Calendar Attributes on Reload
  custom_components/recycle_app/calendar.py
Labels: bug [beta]

#52 Add Textiles collects
  custom_components/recycle_app/const.py
Labels: new-feature
