Repository olibos/HomeAssistant-RecycleApp, pull requests merged in 2025-01, with the labels that each got.

#93 🔧 Improve Fraction Detection Logic to Prevent Misses
  custom_components/recycle_app/api.py
  custom_components/recycle_app/config_flow.py
  custom_components/recycle_app/strings.json
  custom_components/recycle_app/translations/en.json
  custom_components/recycle_app/translations/fr.json
  custom_components/recycle_app/translations/nl.json
  custom_components/recycle_app/translations/sk.json
Labels: enhancement

#102 🔧 Fix recycling park ZipCode retrieval
  custom_components/recycle_app/__init__.py
  custom_components/recycle_app/config_flow.py
Labels: bug

#104 chore: Device models name change and configuration url added
  custom_components/recycle_app/__init__.py
  custom_components/recycle_app/calendar.py
  custom_components/recycle_app/const.py
  custom_components/recycle_app/sensor.py
Labels: enhancement

#103 Feat: Added new state attributes to provide day of week information
  custom_components/recycle_app/opening_hours_entity.py
Labels: enhancement

#99 feat: entity_id_prefix
  custom_components/recycle_app/__init__.py
  custom_components/recycle_app/calendar.py
  custom_components/recycle_app/config_flow.py
  custom_components/recycle_app/opening_hours_entity.py
  custom_components/recycle_app/recycling_park_calendar.py
  custom_components/recycle_app/sensor.py
  custom_components/recycle_app/translations/en.json
  custom_components/recycle_app/translations/fr.json
  custom_components/recycle_app/translations/nl.json
  custom_components/recycle_app/translations/sk.json
Labels: new-feature
